### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TetroYT** [iZeaoGamer/Koth-v3.0#1]
when i type /koth in game it says cant run that 
![EFABF9F1-EAD2-4A10-80C2-454CBA87344E](https://user-images.githubusercontent.com/49662383/73733583-2605b080-4734-11ea-93e1-2c91ac4fa05f.png)
in console even though its been done in game

**Comment by iZeaoGamer** [comment]
What is the player-creation option set to in your config.yml?

**Comment by TetroYT** [comment]
false

Im guessing it needs to be set to true?

**Comment by iZeaoGamer** [comment]
Yes.

**Comment by TetroYT** [comment]
thank you and i have one more question, what is the difference with setgametime and seteventtime

also when i type /koth setgametime 10 it says Koth Game Time set to 10 minutes (200 seconds) but 10 minutes is 600 seconds

**Comment by iZeaoGamer** [comment]
Okay, I will make a clarification regarding this soon.
But let me brief you the difference between gametime and event time.
Gametime, is how long the koth game lasts for.
Event time, is how long until an koth event starts.
Also, during the coding phase, I was trying to translate minutes to seconds. What I did end up doing, was translating the minutes to ticks.
I will try to re-code the translations for this soon.

**Comment by TetroYT** [comment]
ooh ok thank you and this isnt the right place but do you fix broken/outdated plugins that arent being supported by the developer anymore? i have literally one plugin on my server that needs to be fixed so it can be released

**Comment by iZeaoGamer** [comment]
I can do, what’s the plugin called? And the link to it?

**Comment by TetroYT** [comment]
thank you so much its called piggy book system, it has been forked by someone else since release but it now doesnt work 

https://poggit.pmmp.io/ci/haKingdomsCraft/PiggyBookSystem/PiggyBookSystem (this is the forked version but i can get the original if you prefer)

**Comment by iZeaoGamer** [comment]
The original version would be much appreciated. Thank you.

**Comment by TetroYT** [comment]
https://poggit.pmmp.io/ci/goldentouch74/BookSystem/PiggyBookSystem

**Comment by iZeaoGamer** [comment]
Okay, I’ll check it out shortly. Issue closed.

**Comment by iZeaoGamer** [comment]
@TetroYT I have updated the plugin to v1.2. You can grab the latest .phar file here: https://poggit.pmmp.io/ci/iZeaoGamer/PiggyBookSystem/PiggyBookSystem
Issue will be closed from a few hours to a few days depending on if or when you’ve seen this or not. Thank you, and enjoy!

## NOTE
If you have any issues with the updated plugin, please report issues to the forked and updated repo. Thank you.

**Comment by TetroYT** [comment]
thank you so much ill see if theres any bugs now

**Comment by iZeaoGamer** [comment]
Okay! No problem! Issue closed.
