### ISSUE TITLE
2 Issues

### ISSUE THREAD

**Issue by TetroYT** [iZeaoGamer/Koth-v3.0#11]
when i started capturing the area it started at 95% and went to 100% really fast then crashed

secondly 
![0BCCF089-9778-4060-9533-EB05B08365A9](https://user-images.githubusercontent.com/49662383/74223388-7ccc3680-4cae-11ea-9669-b99062623204.png) its spamming this in the chat

**Comment by TetroYT** [comment]
nvm the spam was my fault but theres still a crash after 100% capture

**Comment by iZeaoGamer** [comment]
Please send the error / crashdump log.

**Comment by TetroYT** [comment]
PocketMine-MP Crash Dump Tue Feb 11 15:05:56 CET 2020

Error: Undefined property: koth\KothArena::$fac
File: plugins/Koth-v3.0_dev-35.phar/src/koth/KothArena
Line: 244
Type: ErrorException

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: KingOfTheHill v3.0.0-ALPHA2

Code:

Backtrace:
#0 plugins/Koth-v3.0_dev-35.phar/src/koth/KothArena(244): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[40] Undefined property: koth\KothArena::$fac, string[75] phar:///home/minecraft/plugins/Koth-v3.0_dev-35.phar/src/koth/KothArena.php, integer 244, array[3])
#1 plugins/Koth-v3.0_dev-35.phar/src/koth/KothArena(201): koth\KothArena->won(object koth\KothPlayer)
#2 plugins/Koth-v3.0_dev-35.phar/src/koth/GameTimer(60): koth\KothArena->checkPlayers()
#3 src/pocketmine/scheduler/TaskHandler(169): koth\GameTimer->onRun(integer 8040)
#4 src/pocketmine/scheduler/TaskScheduler(206): pocketmine\scheduler\TaskHandler->run(integer 8040)
#5 src/pocketmine/plugin/PluginManager(703): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 8040)
#6 src/pocketmine/Server(2670): pocketmine\plugin\PluginManager->tickSchedulers(integer 8040)
#7 src/pocketmine/Server(2403): pocketmine\Server->tick()
#8 src/pocketmine/Server(2250): pocketmine\Server->tickProcessor()
#9 src/pocketmine/Server(1811): pocketmine\Server->start()
#10 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)
#11 src/pocketmine/PocketMine(297): pocketmine\server()
#12 (1): require(string[68] phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.11.4 [Protocol 389]
Git commit: 13f28d8454fc499e1869190ccbbad077bff5853f
uname -a: Linux 7ee55bdf66a2 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64
PHP Version: 7.3.6
Zend version: 3.3.6
OS : Linux, linux

Loaded plugins:
ItemDropText 1.0.0 by AlexItz16 for API(s) 1.0.0, 3.0.0, 4.0.0
Slapper 1.5.2 by jojoe77777 for API(s) 3.9.0
VirionTools 3.3.0 by JackMD for API(s) 3.0.0
CustomBooks 1.0.0 by AytgDmr1 for API(s) 3.0.0
WorldLoader 1.0.0 by JackMD for API(s) 3.0.0
EnchantUI 0.5 by UnknownOre for API(s) 3.0.0
AutoInv 0.0.10 by JackNoordhuis for API(s) 3.0.0
PurePerms 1.4.3 by 64FF00 & ProjectInfinity for API(s) 3.0.0
Trade 1 by Only FurkanGM for API(s) 3.9.4
GrabBag 2.4.3 by aliuly for API(s) 3.0.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
CustomShopUI 4.0.5 by SaltyPixelDevz for API(s) 3.0.0
WorldGuard 1.0.5 by Chalapa for API(s) 3.0.0
AlwaysSpawn 2.2.4 by Philip Shilling for API(s) 3.0.0
BetterVoting 1.6 by Twisted for API(s) 3.0.0
Tebex-PMMP 2.1.0 by Tebex Limited for API(s) 3.0.0
VanillaCoordinates 1.0.0 by Shelly7w7 for API(s) 3.0.0
Wilderness 0.0.1 by  for API(s) 3.0.0
EasyHomes 1.0.2 by JackMD for API(s) 3.0.0
AuctionHouse 1.0.7 by Shock95x for API(s) 3.0.0
TitleADR 3.0.0 by padreon for API(s) 3.0.0
NanoCombinerGUI 1 by ItsGabry for API(s) 3.0.0
FormAPI 1.3.0 by jojoe77777 for API(s) 3.2.0
TopVoter 3.2.0 by SalmonDE for API(s) 3.0.0
RankInfoUI_By_NaufalBlaze 1 by NaufalBlazeYT for API(s) 3.0.0, 4.0.0
MysteryCrate 9.1.1 by JackMD, DaPigGuy for API(s) 3.9.0
TopMoneyUI 1 by ExecutivAC for API(s) 3.0.0
SpawnParticle 0.1 by PawarenessC for API(s) 3.0.0, 3.8.0, 4.0.0
VanishV2 1.5 by superbobby for API(s) 3.0.0
StaffChat 1.1.4 by Thunder33345 for API(s) 3.0.0
CombatLogger 0.0.6 by Jack Noordhuis for API(s) 3.0.0
PocketLotto 1.1.1 by ProjectInfinity for API(s) 3.0.0
AutoClearLagg 3.0.0 by Twisted for API(s) 3.0.0
WorldBorder 1.0.0-3.0.0 by ArceusMatt for API(s) 3.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0
PlayerVaults 3.2.0 by  for API(s) 3.0.0
DontCraftItem 1.0.0 by alvin0319 for API(s) 4.0.0, 3.0.0, 3.5.9, 3.5.8, 3.5.7, 3.5.6, 3.5.5
DevTools 1.14.0 by PocketMine Team for API(s) 3.11.3
ScoreHud 5.1.1 by JackMD for API(s) 3.0.0
KingOfTheHill 3.0.0-ALPHA2 by iZeaoGamer for API(s) 3.0.0
WorldTP 1.2.1 by Thunder33345 for API(s) 3.0.0
HeadHunter 1.2 by iCirgio for API(s) 3.0.0
MiningRewards 1.5 by David for API(s) 3.0.0
BanSystem 1.0.0 by Sam for API(s) 3.0.0
ExplosiveEnvoys 1.0.2 by GiantQuartz for API(s) 3.0.0, 4.0.0
CustomDeaths 1.0.0 by ArceusMatt for API(s) 3.0.0
PiggyCustomEnchants 2.0.4 by DaPigGuy for API(s) 3.2.0
CoinFlip 0.0.1 by KingOfTurkey38 for API(s) 3.0.0
BuilderTools 1.2.0-beta2 by CzechPMDevs, VixikCZ for API(s) 3.0.0
WarpUI 1.2 by Lover_BOY636 for API(s) 3.0.0, 3.1.0, 4.0.0
BurgerSpawners 0.0.5 by Heisenburger69 for API(s) 3.0.0
BossSystem 1.1 by sLeeD for API(s) 3.5.9
SellSystemXAndrei52 1.3.0 by AndreasHGK for API(s) 3.0.0
PCFly 3.0.0 by Angel for API(s) 3.0.0
NanoBinGUI 1 by ItsGabry for API(s) 3.0.0
CommandBlockerX 1.0.0 by Twisted for API(s) 3.2.0
BlazinFly 1.8.7 by iiFlamiinBlaze for API(s) 3.0.0
Bounty 1.1.2 by Jackthehaxk21 for API(s) 3.7.0
DropParty 1.0.0 by Netstarv2 for API(s) 3.0.0, 4.0.0
OnlineTime 1.3 by Zedstar16 for API(s) 3.0.0
EasyKits 1.1.3 by AndreasHGK for API(s) 3.9.0
SimpleTPA 1 by TheOriginDeveloppement for API(s) 3.0.0
BlazinBroadcasts 1.0.3 by iiFlamiinBlaze for API(s) 3.0.0
MOTDShuffle 1.1.6 by TheDeibo for API(s) 3.0.2
PlayerJoinSettings 3.0.0 by Anders, wode490390 for API(s) 3.0.0
PureChatExtras 1.0.0 by ProxyTechDevs for API(s) 3.0.0
BookSystem 1.2 by GoldenTouch74 for API(s) 3.11.0
LevelUP 1.0.0 by zZPROGAMERZz423 [] Version 1.0.0 DEV [] for API(s) 3.1.0, 4.0.0
Relics 1.0.2 by TheAz928 for API(s) 3.0.0
LuckyPot 1 by FreakingDev Fixed By ZulfahmiFjr for API(s) 3.0.0, 4.0.0
AutoEXP 0.0.1 by RubyTemple for API(s) 3.0.0
RepairRenameUI 1.0.1 by bumbumkill for API(s) 3.0.0
SupplyCrates 1 by Amon for API(s) 3.0.0
FactionsPro 2.1.6 by Tethered_, edited by VMPE Development Team for API(s) 3.0.0
QuestPMMP 1 by Gamchik for API(s) 3.0.0
TopFactions 1.0.0 by Jackthehack21 for API(s) 3.7.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtXFtz2ziy/iss7dRWUse63/2QKvma7Nhjra1kZzNMuSASkhCRBAcEbclb899Pg1cAkiVKZvac
h0x5IrJBNr4Gmn0DyP9UZpS5iD8+YRYQ6lVOWycVTlxcOW12B81Oazjs9k4qDgr4JWOUVU7/U+Fr
H5or0fnlysI+FzeeVFwcBGgumj57Np4RD9uGz6iPGV+fGkvKF6b5K/w7YthDp6e/zJAFd81Cx7ki
jrjNXyB2Wq/XF9TFdRfutxia8brvhHPiBXVxb/WpXWs82vip2u7WxPX1gFl1wbuesQa6LxgnTA+8
G+50oGsYiE4HhoIhC47/qPytYRzK6R1weH9q+NRaYi7EMc2QEycwzc/i5/QUKyP4EXm2g9k74nE8
x8wYnBgBZ8Sb/9FpfDMKD2l2V7/7zShxRE+MFJgYGAMxhtZ/tL+9h/H6W/OIsWk0329IUP3wTL13
dPodW1xqGztojVnUU6toT9fIxRPQY/au19jWkbXA1jJmHLyLWLcNcXM+W/UArrFDmJL6BAXLdHqa
vWHGL+uk+oF696GXz12j04iYdnYzfUjPYDx6mq5kV5qm1H/1A9vWT1fvJx6m+jj6uUUePJjsXb/R
3t1Jhqf6wUXEmywYRvZHjBifYsQ3u+3p3T5g9iSk6fUbWk8xINNUEFU/cGLlvQabPfRf66GzIUvc
ErOMp3Tw2s2tbmPHzWNGLbBllMVchq9waQ6azVe4BByGLL672dBvH0eHt3D4rtXvvMLh8dGiHjzJ
ocXTB+IMBfgcLHFwQ5GN2YmR0LcYmFuYvBs6n4urEnPQ7H0zdDuQNbY6m43pgxZL0dwlxbCvq1U8
QvGtLeOdGCeG/wwJw++SLnuD181Txil/qLf2LOzS+8q3v04q+Ac5p7f7EAAX3/5IvCfqPGEXexx4
2jAWFq+krUD5FYblbjZZ4I/EcaDBorZwPd9+eqGfXuinF/rphX56of/XXuikMsceZsgRbshDIoWq
5BdVb8cAYwqDl6dalXat2ax1BD0kjg0pV38wOKmQQBiTyukMOQEG/8AopxYFtu3BEDohwns027PW
wB50up2Z1RkOcXPQGzaHDcuaTpHd6Pens1l30G3PgDdDS4dM4Z5GrdmqNYASJuhuiBeujD7G3e7U
nvV6qGV0as1hrVHtVZFr9zoG2NSH27FxgacEeXFjr19t/Y+Np81GCEMKBnRYbTbh772xGvQee0Ia
kX+dVvq1dq0HZy/YsyNZ41NofKRB2jsQohMnOsl8ZSDG8BPH7gW4mQlecWlMFfJJJR/NZq0RiYdC
vqAsEP5y5ODVJ/7S7InpQT4RtPSydvLbiX6hHSzy1MGAFfQdxt3GPiAPYg8c0Bm/kAnCMCVgBJBY
2YXfh6dCTPzdw+Rfd/c3F0B6xtOAcAFdCPjgIB88pyRQSlFl6dZaqizf6XeK++I/SZh2bXg8+CDu
uBj2Bed+AI8J6N8inNYs6tZzRPVUBhDwC2Egw4RSJ5CElKmyoEIttEn7B7KWtxeKkG+YoZibaUoA
lJMic3YeBpy6Z5QuZZFk6j49XPP5hcuaZQmV8jNNCURxHfwXZY4d229JHpm6R54fM0USAOWkiEiX
nrVAHv/8SRIop8niNGpdVZjP3tKjz94dw2UJlHM0zQxE8ekZhZx+8p4kSVKKKgcY9C3z8hulzF6E
JChLmu/A1EuZmiZ0RyGVMc0c1F6JxiHDY8xc+fHJaaqydWptVahe5+qq0TD+bkBEJEKNTx6kIISv
y5LvMe4AgsIUkXR4hFmM7k3ClpwPjMKEIZHRZSMQnyvSq5Lfec7auArZEnnXt5rV7xwrbsoPYm3R
f3G1vGZoeobmkgApRRahtTmByCGh88bpqlyhgANgL5iBQciliXmb5hygTNH8aF92C1HhjGDHrqdC
CaMC0S9116OxYlVyoix3t9bXPTb18BT+L0tPE3amiWMEwBPMi4ymoCN7WFBfMZQKWRZKxEaatXxA
Dl+PyQo7F/jp5SDZ5KHbIafaQ+riYnRPLUhO4KjIDMMEB4KVL1jV5ijzfNchYrbu+GKi7vc04c8X
CAIdVNaMJuya7cTdRRjk4yMUOeMZeRLnGa2DBx89e7I3kajqo9uKshFJ4PGCOMQ3HuAHQvR5WYL7
Edsg4Qo+JUIUCESmqTv9h8nofvJ5vKHMZ5hzzL5QLoDl0ilkdT57qnCTZxJwQF6SUAk705QRqGdF
ntEJnuJVdXwLCaPkKnKiOmNNPTSLrjRuiEtKFO0sXEdJMTjGLKMFyRJq7OyKyPYFeTDl6FxEE8RD
HCspwmbjnjD0YYEdZ91/7pclZ5AyhBRhA82mZu6IsCGfx8zDgSygRNwI5BTBSpLGDf8ESKb5nPUL
tkXGsD+qRsH6I3WVacpp+uy0/htJQtb9IfG0FZW2aRhgJaiWyLosfV3TQO+H3dUbgxjVAWZKF/MW
oXWEaCEQifhawbffcBDu4NHFvWw2UpKacm88SD6yGYbGssx7zA4iTMJjAMUn6zfk0XPqTsHCsGsl
StFbdgTOn3hwjaZs/SPCk5S3aWqAist4RZmrBpUpRVXDjdLIKzWg1huSu4yjaSYgsoNCSkd9cG1K
HSEjqUrX2rDeyHGpd3H5xmcq9kiix4oSQ0a8QQUTNPlREbHukbeEPJN+/vR4tn78DYUz5Jw56EW2
H69fs0Mzpcv+PdmQ/I3VSIW5aeYAi6vm7RpiGLY+Z4jLsipkWbwhRCDNrXb/pHKBxmR+Ha7Lqlem
LkAGc3TCFzOrK4LF+nwLSdZasTwSccfUXq6wFXLyNDovy44iyzQ59Q8oLosIeowYJ5YjT59KV4MP
TYoxekYMiwDhfIt6tmuDt6upn3UB8kVBv59AKy6pCM+CxZeWFj9GJK2QrsoXhD5mUzqdllY/yjnG
UaPAkB8VmjaOZjNI3ORljpymitPUU7TJIvQgpGu3251uaamMxBMS7hSKdHjEE5cwvaA4SMtjOTtR
nABXini8YCgXJ2SyHjf3Nk2P8aMLoFYEyIkAmaYGb38pNHJXN5RzurFQGFP1+dYf0DKroLL3zOpd
rcrJ9khV6zrNBiPYyknRKve5gxG7QfO5VuvO6XsC15JTeJ6m8KLIbQkQDoCIS90ypoNVP+Y7CtZO
6N6e11V+aV3qDFRsc0UmoW6kwtUtwzFiFg6DW8R5WSMiQTja1aIIlStQJWsBmq3LSPpKQLO5bSng
sKg+L8FvKypHKVYAig0d/Y6fCCRb48tqSq+8skoQG0MJ9lvXCFIbGO8F+oJChytrJTJ5d1hdcu3A
j3p+inoW22YUHHuf8Qvq8XNRIhLr5JI8Kn1PlQc5T8RrtJtDad472iJ+u9atDZPfQfLbT357yW/3
2LFQ0JqmDn7/KOAnfTk8I2nGvqMLn9fbjAlGrqL6TcgQj5YpAQDi5FB2FFy36XAGrZ7xEMGMRRn+
GMoF9oykLpi8ljmUXDFKe8+Pikyauhszl0Xfpam5p+roZvxxpFXCyFeMqNimx8qSLd9JeNCa/2Ss
e5fJWFPBlj4pPz6+TIBkB+XElikzkP2j2D8YemqZQiJqI6BN3jlhc0J/RCmJWBFr08yxHFJkhkcP
lPEeQzZly8ZFpe/Mhi7QEykterIFM9N0o+5Z3P0ByznIexDJuOwnctq+lQDNNL5BiinygqhP05S7
318rX/kODcgTvvSe6FqpmGste+rm1wR5/J8hpMQvZReINCSmuQmt4BryBUZ8sbkbKiHv2w5Vepgq
915WnErm83XMN9nDo0RkW1rVlbmGnqhvLYe9oXSb8oOwbBPMVmKh6aXEu3KIr2TgCWn3qlXqGkO2
xOv24EcYTLUHkXzHyI6ect91fSmQqcqBzFkYrZXpoZtC1n1nozrFHGkP9PkLthbjW+AtbvhCVmR5
/rUszbcEc9+1gblpTmNsPI7sNKQH7yTIYdcVViKaQEzdQpIQdnrSGwqNj2d3/+61e1tri823W7gY
R/E64lnI5phF9VHM1GlWGnTV1/zoR0wC7E2je3rDsuZW5SomVMZ0tNJrYMUo0CDYdL45UctStIrq
DcZq0C5ysWN3GtDgoIX2B+w4McjfR57NMOnKJeFtrXuW2KLrUPDx+tcfYcBy7uIlC8cZOU52UKh6
eH7lrGU3FJ3vKZKNvDl2Stt6LJiBdxEdH7aqe0a8zQXdhFj2Wm7h9dsz8TZQUSnOqesizz5zhMNg
v6tFaqVlTwC0rWzZKqFsacUwpjGMVVSd1nAVMhYJQxTVK12r5kZrY2JhUfhbWQFzmiryQN9BQciV
g1xCvHiJtKTJVLmChUzhSIeF3ACF7EuRKybotfgtW1z4Ai/QatlSN/f3y7EXogMQJQJTXE/F6zFi
tU8WKKft0c3fMBcvjj21yk4+bEAgFvpAEBnMXmnuPPEy7ST6KEUmjkTUDLoqzVdsC2mavbI0LmNo
mjmGo11xxq0uCZRsvPqVcH3fVUTSdbJdyIEN37JZ6aRyGzqcJJTK9uRou5dLYedHBffuLuZLsDv1
yMkT13fwZDySXXtG2+E7Jgt8x8iceBDEYgfUL377uqwqFuQdEx8dVa7aiiuzsWcMGFooUBRgo0l/
kNv/dxY3R7VJKVTKuptcPCzC2UzZtiBTda3vbcz0BSZTvUzXOlZMqWv94X6tgBUvjvwDUtIHzMVu
380VHKVxb9Rmx4nHM7VxZ9hoDxvlxXB2lD9sgiruY9JVq8sVZyjYspiXNOzxNmNGV+sJJJpRdnzw
wl60brZDUoV9vmIXY9PPiwUKdLklU8qIOxPgawpJtDehobXod/SlnH3Sbre4rwk+j7ricVcigkgR
Fp/hG2GbPssrBillz5y+fB3f312Pbi/vv750Wm3jj2/Gl/h6I7rauLj8AkR1AN4eXyToigt4jx1i
yaqbEPbUZ8HUjF6GrUF5iyExP9OM+09/C81RaC3XYyovpmekHX7xCtzzEp53eCqMK7LCtnG2Nr6G
zgwtXHL1nZUd+qWYDnsH8vL3sbYvRFD2FCHvwyk88CI2KGt+co7xRhAAcYiO+YiweyyEUJJfrUHX
OU2qaejC31IsOR5blci3He+QlbEDNhuGvu/EOyflh0gh79DBkVvehnO5zwO2YUu7P6St2MqeEPVd
Gz3owJD8MWw/nhjYFu/bGNO18eV2fGkkcZ2I6jbX7Y/YpZXvNBl5nDz4yI3hbd2mJUlgmslJ0TH5
Z4gDrr18lNN2TOc1cq0FWZYWojh4dcZEcSbq3TT/FD9BwS3p2f4dZQ9vRi3wdnuU1VsHZ/Wy8uxJ
67Meop3p6Y1FtVd8KiP/QMnadQQVOow+eVJLvs5ExIMpyJB2wyhwnO4QwiuOvSAdoXPKsPTBDjva
+p2dAicvCByJ4lvK9cGfDqBqy5/8iD84kp5OLRfxhUSwkANDgphMYmtf7IgEk96OjJ+VfMkruyBk
MobvQTJ7/Wj2ZsSJVvez9hmXv0Eyt+UTV25aoECGBtm4QCZf/zC+kc4c8WTb8fdU4r0S7jT+mIx0
kbuGQYk+e5IcGV1h01tVGxxu1Wg1mt1Gp9GHw18+2adG37Lgb9jDvX531rP7Ldy1Zo1Zq9efdQa4
2etbLTSdQiT1SzT6HpdHYrxQBjLXikdrEXrL6Fs88UbvaKR8GpCVfD2PPq8UJJvJmuLTMycVhmG8
hYLM43dls9vvMWREkarKg7ZwqTymQYQhkHUqSBbIxCYtMp8SD7F1kveIMeR0iT3yokzhGkVana6k
vog1SZH6daPTaGBJdvlff/0vyVB7Jg==
===END CRASH DUMP===

**Comment by TetroYT** [comment]
also i dont think the config works, in the config i have game time set to 600 but when i play koth it says 60 minutes 
![E44358C0-B74E-4E9A-BC0C-43479420FFC5](https://user-images.githubusercontent.com/49662383/74243599-f75d7c00-4cd7-11ea-9960-afd6f00dd4d0.png)

**Comment by iZeaoGamer** [comment]
Please try using the latest dev build.
