### ISSUE TITLE
.

### ISSUE THREAD

**Issue by TetroYT** [iZeaoGamer/Koth-v3.0#17]
idk if you accidentally did this or it was for testing or something but with discord webhook it says what im guessing is your servrr
![038E16C4-E882-455D-9790-752A98043D51](https://user-images.githubusercontent.com/49662383/75177826-c85ef580-572e-11ea-8a0a-38b71f2b2c45.png)
 and its not changable in the config

**Comment by iZeaoGamer** [comment]
Oh, whoops. Will fix shortly.

**Comment by iZeaoGamer** [comment]
Should now be fixed. Note that soon, I’ll be implementing a messages.yml file, where you can edit the messages of the plugin.
