### ISSUE TITLE
Event time resets to 3 hours

### ISSUE THREAD

**Issue by ExpertMCking** [iZeaoGamer/Koth-v3.0#2]
Hi, the koth event time resets to 3 hours whenever I try to set it to 2 minutes. The description of the command it says /koth seteventtime <game-time-in-seconds> however when I ran /koth seteventtime 120 and restart my server it says 2 hours when I run /koth join. On the second time I reseted the plugin data and did /koth seteventtime 2 (thinking that it might have been a typo in the  command description) however it resets to 2 hours upon restarting the server. 

Besides this, may I ask if this plugin has non-factions support, meaning that I can use it without factions pro? Thank you!

If you have any other queries please contact me at my discord ExpertMC king#1939

**Comment by iZeaoGamer** [comment]
Hi!
I haven’t actually tested this without factionspro support yet.
I guess you could go and see if that works without the need of factionspro.
And with the issues you may been experiencing, I will see to a fix soon. Though, this never occurred for me, but I shall check the code to see the cause.

**Comment by ExpertMCking** [comment]
Okay thanks!
If possible can you make factionpro support optional? That will be awesome thanks!

**Comment by iZeaoGamer** [comment]
I believe it is already optional. Try to test it to see if it works without factionspro.
If this doesn’t work, please send me the full error log.

**Comment by iZeaoGamer** [comment]
Okay, this commit https://github.com/iZeaoGamer/Koth-v3.0/commit/0412b3837d713054df79279d8aba5587c387a81b should fix your issue.
If not, please let me know and I’ll reopen your issue. Thanks.
