### ISSUE TITLE
same issue 

### ISSUE THREAD

**Issue by xVolar** [iZeaoGamer/Koth-v3.0#26]
Error: A non well formed numeric value encountered
File: plugins/Koth-v3.0_dev-62.phar/src/koth/arenas/KothArena
Line: 342
Type: ErrorException

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: KingOfTheHill v3.1.0

Code:
[333] 
[334]     if($percent > 94){
[335] 
[336]      
[337]       $this->addTitlePercentage($p, $percent);
[338]       
[339]     }
[340]     }
[341] 
[342]     public function addTitlePercentage(Player $player, int $percent){
[343]         Server::getInstance()->broadcastMessage(KothLanguage::getMessage("CAPTURING_POINT_MESSAGE", [
[344]             "{percent}" => $percent,
[345]             "{player}" => $player->getName()
[346]             ]));
[347]     }
[348] 
[349]     public function endGame(){
[350] 
[351]         foreach ($this->players as $player => $time){
[352] 

Backtrace:
#0 plugins/Koth-v3.0_dev-62.phar/src/koth/arenas/KothArena(342): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[43] A non well formed numeric value encountered, string[81] phar:///home/gs-41393/plugins/Koth-v3.0_dev-62.phar/src/koth/arenas/KothArena.ph, integer 342, array[2])
#1 plugins/Koth-v3.0_dev-62.phar/src/koth/arenas/KothArena(311): koth\arenas\KothArena->addTitlePercentage(object koth\KothPlayer, string[2] 1%)
#2 plugins/Koth-v3.0_dev-62.phar/src/koth/arenas/KothArena(207): koth\arenas\KothArena->sendProgress(object koth\KothPlayer, integer 1)
#3 plugins/Koth-v3.0_dev-62.phar/src/koth/tasks/GameTimer(49): koth\arenas\KothArena->checkPlayers()
#4 src/pocketmine/scheduler/TaskHandler(134): koth\tasks\GameTimer->onRun(integer 5246)
#5 src/pocketmine/scheduler/TaskScheduler(176): pocketmine\scheduler\TaskHandler->run(integer 5246)
#6 src/pocketmine/plugin/PluginManager(643): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 5246)
#7 src/pocketmine/Server(2380): pocketmine\plugin\PluginManager->tickSchedulers(integer 5246)
#8 src/pocketmine/Server(2143): pocketmine\Server->tick()
#9 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
#10 src/pocketmine/Server(1584): pocketmine\Server->start()
#11 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[15] /home/gs-41393/, string[23] /home/gs-41393/plugins/)
#12 src/pocketmine/PocketMine(296): pocketmine\server()
#13 (11): require(string[95] phar:///pro/bin/mcpe/pocketmine-stable-1.14.60/PocketMine-MP.phar/src/pocketmine)

PocketMine-MP version: 3.12.0 [Protocol 390]
Git commit: 77d45bf11674a1360f58e32a14a3b09f423d860c
uname -a: Linux d9ff1b071743 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64
PHP Version: 7.3.7
Zend version: 3.3.7
OS : Linux, linux

**Comment by iZeaoGamer** [comment]
Please send the main error log, not the debug messages.

**Comment by xVolar** [comment]
I edited it .
