### ISSUE TITLE
Error with discord webhook

### ISSUE THREAD

**Issue by ExpertMCking** [iZeaoGamer/Koth-v3.0#3]
Hi, I didn't want to use the discord webhook so it gave me this error:

Error: "Class 'CortexPE\DiscordWebHookAPI\Webhook' not found" (EXCEPTION) in "plugins/Koth-v3.0_dev-15.phar/src/koth/DiscordIntergration" at line 9

**Comment by iZeaoGamer** [comment]
Try putting discord support to false, and see if that works.

**Comment by ExpertMCking** [comment]
okay!

**Comment by ExpertMCking** [comment]
still gave me an error

**Comment by iZeaoGamer** [comment]
Okay, will try to fix this ASAP. Thank you for reporting!

**Comment by ExpertMCking** [comment]
No problem!

**Comment by iZeaoGamer** [comment]
This bug should be fixed in commit https://github.com/iZeaoGamer/Koth-v3.0/commit/80f3162629ac37765f41aaceb38e37b9fbf633aa
Thank you for reporting, and enjoy!
