### ISSUE TITLE
Event timer not decreasing

### ISSUE THREAD

**Issue by ExpertMCking** [iZeaoGamer/Koth-v3.0#4]
Hi another error! The event timer does not seem to decrease. Mine was set for 2 min and up to now there is no message and when I run /koth join it says There is no koth event happening at the moment. The next game begins in 00:01:59. Also the kothinfo.yml says the event time is : 119 . I kept refreshing it but it still remained the same.

**Comment by ExpertMCking** [comment]
Must I update anything in the config or?

**Comment by iZeaoGamer** [comment]
Try with the latest dev build that just released. Should be fixed.
