### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TetroYT** [iZeaoGamer/Koth-v3.0#5]
I keep getting this crash with webhooks i tried setting it to false in the config after the first crash but i keep getting the crash
![70F145E0-DC61-4F90-8ECF-8C29054B720F](https://user-images.githubusercontent.com/49662383/73766209-9b41a780-476d-11ea-9110-9422bb7f5247.png)

**Comment by iZeaoGamer** [comment]
Please update to the latest dev build. You're currently running Dev build 1, which is outdated. Issue closed.
