### ISSUE TITLE
Notice of copyright

### ISSUE THREAD

**Issue by JaxkDev** [iZeaoGamer/Koth-v3.0#6]

**Comment by iZeaoGamer** [comment]
Okay, you do realize this plugin's code was originally from the Koth plugin by Tethered, the one that got all buggy. Surely you've heard of that plugin? It was made way before your koth plugin.

**Comment by iZeaoGamer** [comment]
I just updated, and revamped it to work with the latest pocketmine versions.

**Comment by iZeaoGamer** [comment]
Please elaborate which part I "copied".

**Comment by JaxkDev** [comment]
Got a link, can’t find a tethered ?

**Comment by iZeaoGamer** [comment]
Oh, that. I forgot to remove the code, I had this plugin beforehand, which I was testing. It's commented out. I shall remove that part of the code. Sorry about that

**Comment by JaxkDev** [comment]
Even if it was from a ‘tethered’ you should probably check their license 👍

**Comment by JaxkDev** [comment]
Also you shouldn’t have my code if your on that plugin....

**Comment by iZeaoGamer** [comment]
Okay, I've fixed it. Sorry about that.
Also, this plugin was broken. So I had to fix it.
I won't do it again. Apologies.
