### ISSUE TITLE
Another crash

### ISSUE THREAD

**Issue by TetroYT** [iZeaoGamer/Koth-v3.0#8]
![28586557-F90C-47E2-A601-7A3E4210E847](https://user-images.githubusercontent.com/49662383/73771487-62f29700-4776-11ea-86ae-105321f1417d.png)
im doing nothing to cause this it just happens

**Comment by iZeaoGamer** [comment]
Please send me your config.yml file.

**Comment by TetroYT** [comment]
i removed it because it was crashing my server every time i started, the only things i changed was discord support to false game time to 10 minutes and event time to 3 hours
